create database supply_chain
use supply_chain
select * from Supply

-- Write a query to calculate the total revenue generated by each product
-- and display the results in descending order of revenue.
select product_name, sum([Total_Value_USD])as Total_revenue
from Supply
group by product_name
order by Total_revenue desc

-- Write a query to find the average delivery time for each shipment mode
-- and display the results in ascending order of the average delivery time
select [Shipment_Mode], avg([Delivery_Time_Days]) as avg_delivery_days
from Supply
group by [Shipment_Mode]
order by avg_delivery_days asc

-- Write a query to determine the top 5 locations with the highest number
-- of orders
select top 5 [Location], count([Order_ID]) as Total_Orders
from Supply
group by [Location]
order by Total_Orders desc

-- Write a query to analyze the distribution of order statuses
-- (how many orders are in each status).
select [Order_Status], count([Order_ID]) as Total_Orders
from Supply
group by [Order_Status]

-- Write a query to find the most frequently ordered products
-- (based on the number of orders).
select [Product_Name], count([Order_ID]) as Total_Orders
from Supply
group by [Product_Name]
order by Total_Orders desc

-- Write a query to analyze the total revenue by month. You can use the
-- Order Date to extract the month and year
SELECT 
    FORMAT([Order_Date], 'yyyy-MM') AS Order_Month,
    SUM([Total_Value_USD]) AS Total_Revenue
FROM Supply
GROUP BY  FORMAT([Order_Date], 'yyyy-MM')
ORDER BY Order_Month;

-- Write a query to determine the total revenue contribution by product
-- category
select [Category], SUM([Total_Value_USD]) AS Total_Revenue
from Supply
group by [Category]

-- Write a query to list all orders that are either pending or in transit.
select *
from Supply
where [Order_Status] = 'pending' or
[Order_Status] = 'in transit'

-- Write a query to find the shipment mode that generates the most revenue
select top 1 [Shipment_Mode], SUM([Total_Value_USD]) AS Total_Revenue
from Supply
group by [Shipment_Mode]
order by Total_Revenue desc 

-- Write a query to find the orders with a total value greater than $10,000
select *
from Supply
where [Total_Value_USD] > 10000

-- Write a query to calculate the average delivery time for each location,
-- and order the results by the average delivery time in descending order
select [Location], avg([Delivery_Time_Days]) as avg_delivery_days
from Supply
group by [Location]
order by avg_delivery_days desc

-- Write a query to find the total revenue generated by each product
-- category and shipment mode.
select [Category],[Shipment_Mode],
SUM([Total_Value_USD]) AS Total_Revenue
from Supply
group by [Category],[Shipment_Mode]

-- Write a query to find the percentage contribution of each shipment
-- mode to the total revenue.
select [Shipment_Mode], sum([Total_Value_USD])*100 /
(select sum([Total_Value_USD]) from Supply) as Percentage_contribution
from Supply
group by [Shipment_Mode]

-- Write a query to identify the top 3 locations with the highest
-- average order value.
select top 3 location, avg([Total_Value_USD]) as avg_revenue
from Supply
group by location
order by avg_revenue desc

-- Write a query to find the month with the highest total revenue for
-- each product category.
with highest_month as (
select [Category],datename(month, [Order_Date]) as month,
		sum([Total_Value_USD]) as Total_revenue,
		rank() over (partition by [Category] order by
		sum([Total_Value_USD]) desc) as Rank
from Supply
group by [Category],datename(month, [Order_Date])
)
select [Category], month,Total_revenue
from highest_month
where rank = 1
order by Total_revenue desc

-- Write a query to analyze the trend of average revenue per order over
-- the months for all categories combined.
select DATENAME(month, [Order_Date]) as Month_Name,
avg([Total_Value_USD]) as avg_value
from Supply
group by DATENAME(month, [Order_Date]),datepart(month, [Order_Date])
order by datepart(month, [Order_Date])

-- Write a query to find the top 3 products with the highest revenue
-- contribution in each product category.
with Top_Products as (
select [Category],[Product_Name],
		sum([Total_Value_USD]) as Total_revenue,
		rank() over (partition by [Category] order by
		sum([Total_Value_USD]) desc) as Rank
from Supply
group by [Category],[Product_Name]
)
select [Category],[Product_Name],Rank,Total_revenue
from Top_Products
where rank between 1 and 3
order by [Category] 

-- Write a query to calculate the total revenue for the year.
select year([Order_Date]) as year,
sum([Total_Value_USD]) as total_revenue
from Supply
group by year([Order_Date])

-- Write a query to find the average revenue per order for each shipment
-- mode and order the results by average revenue in descending order.
select [Shipment_Mode], AVG([Total_Value_USD]) as avg_amount
from Supply
group by [Shipment_Mode]
order by avg_amount desc

-- Write a query to identify the product with the highest number of orders
-- in each location
with Highest_Product as  (
select [Location], [Product_Name], 
		count([Order_ID]) as Total_Order,
		rank() over (partition by [Location]
		order by count([Order_ID]) desc) as Rank
from Supply
group by [Location], [Product_Name]
)
select [Location], [Product_Name], Total_Order
from Highest_Product
where rank = 1
order by Total_Order desc

-- Write a query to calculate the total revenue and the number of orders
-- for each order status.
select [Order_Status], sum([Total_Value_USD]) as Total_revenue,
count([Order_ID]) as Total_Orders
from Supply
group by [Order_Status]

-- Write a query to find the top 3 locations with the highest total
-- revenue contribution.
select top 3 [Location], sum([Total_Value_USD]) as Total_revenue
from Supply
group by [Location]
order by Total_revenue desc

-- Write a query to calculate the percentage of total revenue contributed
-- by each product category, rounded to two decimal places
select [Category], sum([Total_Value_USD])*100  / 
(select sum([Total_Value_USD]) from Supply) as percentage_Contribution
from Supply
group by [Category]

-- Write a query to find the average delivery time (in days) for each category
-- and shipment mode combination, ordered by category and shipment mode
select [Category],[Shipment_Mode],
avg([Delivery_Time_Days]) as Avg_Delivery_Days
from Supply
group by [Category],[Shipment_Mode]
order by [Category],[Shipment_Mode]

-- Write a query to find the most common shipment mode (mode with the highest
-- number of orders) for each product category.
with highest_Category as (
select [Category],[Shipment_Mode],
		count([Order_ID]) as Total_Orders,
		rank() over (partition by [Category]
		order by count([Order_ID]) desc) as rank
from Supply
group by [Category],[Shipment_Mode]
)
select [Category],[Shipment_Mode],Total_Orders
from highest_Category
where rank = 1
order by Total_Orders desc

-- Write a query to identify the products with revenue greater than
-- the average revenue of all products in the dataset.
select [Product_Name], sum([Total_Value_USD]) as Total_revenue
from Supply
group by [Product_Name]
having sum([Total_Value_USD]) > (select avg([Total_Value_USD]) from supply)

-- Write a query to calculate the average revenue per order for each
-- shipment mode, and order the results by shipment mode
select [Shipment_Mode], avg([Total_Value_USD]) as Avg_Revenue
from Supply
group by [Shipment_Mode]
order by [Shipment_Mode]

-- Write a query to find the top 5 products with the highest total number
-- of orders, including the total number of orders for each product
select top 5 [Product_Name], count([Order_ID]) as Total_Order
from Supply
group by [Product_Name]
order by Total_Order desc

-- Write a query to find the month with the highest average revenue per
-- order in the dataset.
select top 1 datename(month,[Order_Date]) as Month,
avg([Total_Value_USD]) as Avg_revenue
from Supply
group by datename(month,[Order_Date])
order by Avg_revenue desc

-- Write a query to find the shipment mode that has the highest average
-- delivery time
select top 1 [Shipment_Mode], avg([Delivery_Time_Days]) as Avg_delivery_Time
from Supply
group by [Shipment_Mode]
order by Avg_delivery_Time desc

-- Write a query to calculate the total revenue for each location and
-- category, and order the results by location and total revenue.
select [Location],[Category], sum([Total_Value_USD]) as Total_revenue
from Supply
group by [Location],[Category]
order by location,Total_revenue

-- Write a query to find the product with the lowest total revenue and show
-- the total revenue for that product.
select top 1 [Product_Name], sum([Total_Value_USD]) as Total_revenue
from Supply
group by [Product_Name]
order by Total_revenue asc

-- Write a query to find the shipment mode with the highest number of
-- orders and the corresponding total revenue
select top 1 [Shipment_Mode], count([Order_ID]) as Total_Order,
sum([Total_Value_USD]) as Total_revenue
from Supply
group by [Shipment_Mode]

-- Write a query to find the top 3 locations that have the highest average
-- delivery time, along with the average delivery time for each location.
select top 3 [Location], avg([Delivery_Time_Days]) as Avg_Delivry_Time
from Supply
group by [Location]
order by Avg_Delivry_Time desc

-- Write a query to find the products with the highest total revenue
-- for each category
with Highest_Category as (
select category, [Product_Name],
		sum([Total_Value_USD]) as Total_revenue,
		ROW_NUMBER() over (partition by category order by
		sum([Total_Value_USD]) desc) as Rank
from Supply
group by category, [Product_Name]
)
select category, [Product_Name],Total_revenue
from Highest_Category
where rank = 1

-- Write a query to find the second highest revenue-generating product in
-- each category.
with top_Rank_Product as (
select 
		[Category],[Product_Name], sum([Total_Value_USD]) as Total_revenue,
		ROW_NUMBER() over (partition by [Category]
		order by sum([Total_Value_USD]) desc) as Rank
FROM Supply
group by [Category],[Product_Name]
)
select [Category],[Product_Name],Total_revenue
from top_Rank_Product
where rank = 2
order by [Category]

-- Write a query to calculate the cumulative revenue for each product
-- within each category, ordered by revenue in descending order.
select 
    [Category],
    [Product_Name],
    sum([Total_Value_USD]) as Total_revenue,
    sum(sum([Total_Value_USD])) over (
        partition by [Category]
        order by sum([Total_Value_USD]) desc
    ) as Cumulative_Revenue
from Supply
group by [Category], [Product_Name]
order by [Category], Cumulative_Revenue desc;

-- Write a query to find the top 3 categories with the highest average
-- delivery time. Display the category name, average delivery time, and the
-- total number of orders for those categories. Sort the results by average
-- delivery time in descending order.
select top 3 [Category], avg([Delivery_Time_Days]) as Avg_delivery_Time,
count([Order_ID]) as Total_Orders
from Supply
group by [Category]
order by Avg_delivery_Time desc

-- Write a query to calculate the percentage contribution of each category
-- to the total revenue. Display the category name and its percentage
-- contribution, sorted in descending order of the contribution
select [Category], sum([Total_Value_USD])*100 /
(select sum([Total_Value_USD]) from Supply) as percentage_Cintribution
from Supply
group by [Category]
order by percentage_Cintribution desc

-- Write a query to find the top 2 shipment modes with the highest total
-- revenue for each location. Use a ranking function to achieve this
with Top_Shipment_Mode as (
select
		location, [Shipment_Mode], sum([Total_Value_USD]) as Total_revenue,
		rank() over (partition by location order by 
		sum([Total_Value_USD]) desc) rank
from Supply
group by location, [Shipment_Mode]
)
select location, [Shipment_Mode], Total_revenue
from Top_Shipment_Mode
where rank between 1 and 2

-- Write a query to calculate the percentage contribution of each shipment
-- mode to the total revenue within its respective location
select 
    [Shipment_Mode], 
    location,
    sum([Total_Value_USD]) * 100.0 / 
    (select sum([Total_Value_USD]) 
     from Supply s2 
     where s2.location = Supply.location) as percentage_Contribution
from Supply
group by [Shipment_Mode], location
order by location, percentage_Contribution desc;

-- Write a query to find the top 3 locations that have the highest average
-- revenue per order. Include the location, the total revenue, the number
-- of orders, and the average revenue per order in the output. Sort the
-- result by average revenue per order in descending order.
select top 3 location, sum([Total_Value_USD]) as Total_revenue,
count([Order_ID]) as Total_Orders,
avg([Total_Value_USD]) as Avg_revenue
from Supply
group by location
order by Avg_revenue desc

-- Write a query to find the top 5 products that have the highest
-- total revenue per category
with top_5_products as (
select 
		category, [Product_Name],
		sum([Total_Value_USD]) as Total_revenue,
		ROW_NUMBER() over (partition by category
		order by sum([Total_Value_USD]) desc) as rank
from Supply
group by category, [Product_Name]
)
select category, [Product_Name],Rank,Total_revenue
from top_5_products
where rank between 1 and 5

-- Write a query to calculate the average revenue, total number of orders,
-- and the highest revenue generated for each shipment mode. Sort the
-- results by the highest revenue in descending order
select [Shipment_Mode], avg([Total_Value_USD]) as avg_revenue,
count([Order_ID]) as Total_Orders,
sum([Total_Value_USD]) as Total_Revenue
from Supply
group by [Shipment_Mode]
order by Total_Revenue

-- Write a query to calculate the total number of orders, the total revenue,
-- and the average revenue for each location. Order the results by total
-- revenue in descending order.
select location, count([Order_ID]) as Total_Orders,
sum([Total_Value_USD]) as Total_Revenue,
avg([Total_Value_USD]) as avg_revenue
from Supply
group by location
order by Total_Revenue desc

-- Write a query to find the average delivery time, total revenue,
-- and total number of orders for each shipment mode. Sort the results
-- by total revenue in descending order.
select [Shipment_Mode], avg([Delivery_Time_Days]) as avg_delivery_Time,
sum([Total_Value_USD]) as Total_Revenue,
count([Order_ID]) as Total_Orders
from Supply
group by [Shipment_Mode]
order by Total_Revenue desc
